name: E2E on Chrome
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
jobs:
  Cypress-Run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: chrome
          working-directory: ./automation
